export const PROTOTYPE_CATALOG = {
  public: [
    ['landing', 'Landing page', 'Public introduction and calls to action', 'landing'],
    ['about', 'About', 'Mission, story, and community values', 'detail'],
    ['donations', 'Donate', 'Campaign discovery and contribution', 'store'],
    ['store', 'Store', 'Product discovery and categories', 'store'],
    ['product', 'Product detail', 'Product media, options, and purchase', 'detail'],
    ['cart', 'Cart', 'Order summary and checkout entry', 'list'],
    ['orders', 'Orders', 'Purchase history and delivery status', 'list'],
    ['order-confirmation', 'Order confirmation', 'Receipt and next steps', 'success'],
    ['login', 'Log in', 'Returning-member authentication', 'auth'],
    ['register', 'Registration', 'Role and account onboarding', 'form'],
    ['forgot-password', 'Forgot password', 'Account recovery request', 'auth'],
    ['reset-password', 'Reset password', 'Secure credential update', 'auth'],
    ['verify-email', 'Verify email', 'Verification guidance and status', 'success'],
    ['faq', 'FAQs', 'Searchable support topics', 'list'],
    ['terms', 'Terms', 'Platform terms of service', 'legal'],
    ['privacy', 'Privacy', 'Privacy and data handling', 'legal'],
    ['conduct', 'Code of conduct', 'Community behavior standards', 'legal'],
  ],
  eaglet: [
    ['home', 'Dashboard', 'Progress and next best action', 'dashboard'],
    ['onboarding', 'Onboarding', 'Goals, interests, and availability', 'form'],
    ['profile', 'Mentee profile', 'Identity, progress, and preferences', 'profile'],
    ['nest', 'Nest', 'Mentor relationship and community', 'community'],
    ['nest-community', 'Community hub', 'Posts, program, and members', 'community'],
    ['mentor-profile', 'Mentor profile', 'Public mentor information', 'detail'],
    ['join-nest', 'Join nest', 'Mentorship request details', 'form'],
    ['requests', 'My requests', 'Mentorship request statuses', 'list'],
    ['learn', 'Assignments', 'Learning modules and tasks', 'learning'],
    ['assignment-detail', 'Assignment detail', 'Instructions and submission', 'detail'],
    ['content-viewer', 'Module viewer', 'Focused lesson consumption', 'learning'],
    ['quiz', 'Module quiz', 'Question flow and completion', 'form'],
    ['leaderboard', 'Leaderboard', 'Points and peer progress', 'list'],
    ['badges', 'Badges', 'Achievement collection', 'grid'],
    ['mentor-application', 'Become an Eagle', 'Mentor application workflow', 'form'],
    ['messages', 'Messages', 'Conversation list and chat', 'chat'],
    ['resources', 'Resources', 'Guides and downloadable material', 'learning'],
    ['settings', 'Settings', 'Account and app preferences', 'settings'],
  ],
  eagle: [
    ['home', 'Dashboard', 'Mentoring activity and priorities', 'dashboard'],
    ['profile', 'Mentor profile', 'Public identity and verification', 'profile'],
    ['nest', 'My nest', 'Nest overview and management', 'community'],
    ['nest-community', 'Community hub', 'Posts, members, and activity', 'community'],
    ['grading', 'Grading centre', 'Submissions requiring review', 'list'],
    ['requests', 'Mentorship requests', 'Review prospective Eaglets', 'list'],
    ['program', 'Program editor', 'Objectives, modules, and rules', 'form'],
    ['enrollments', 'Enrollment queue', 'Approve program participation', 'list'],
    ['learn', 'Content library', 'Published learning content', 'learning'],
    ['content-upload', 'Upload content', 'Create a learning resource', 'form'],
    ['content-viewer', 'Content viewer', 'Preview learning material', 'learning'],
    ['leaderboard', 'Leaderboard', 'Nest progress and recognition', 'list'],
    ['eaglets', 'My Eaglets', 'Mentee directory and status', 'list'],
    ['messages', 'Messages', 'Mentoring conversations', 'chat'],
    ['resources', 'Resources', 'Mentor tools and references', 'learning'],
    ['settings', 'Settings', 'Account and notification preferences', 'settings'],
  ],
  admin: [
    ['home', 'Admin dashboard', 'Platform health and pending work', 'dashboard'],
    ['kyc', 'KYC queue', 'Identity reviews awaiting action', 'list'],
    ['kyc-detail', 'KYC review', 'Evidence and approval decision', 'detail'],
    ['users', 'User management', 'People, access, and account status', 'list'],
    ['team', 'Admin team', 'Platform staff and permissions', 'list'],
    ['role-requests', 'Admin requests', 'Privilege requests and decisions', 'list'],
    ['mentor-applications', 'Mentor applications', 'Eagle application review', 'list'],
    ['nests', 'Nest management', 'All communities and ownership', 'list'],
    ['nest-detail', 'Nest detail', 'Members, activity, and controls', 'detail'],
    ['messages', 'Messages', 'Platform support conversations', 'chat'],
    ['learn', 'Content management', 'Platform learning catalogue', 'learning'],
    ['content-upload', 'Upload content', 'Create platform content', 'form'],
    ['store', 'Store management', 'Products, stock, and categories', 'store'],
    ['orders', 'Order management', 'Fulfilment and payment status', 'list'],
    ['donations', 'Donation analytics', 'Campaign and contribution reporting', 'dashboard'],
    ['points', 'Points configuration', 'Rules, rewards, and limits', 'settings'],
    ['settings', 'Platform settings', 'Global policies and feature controls', 'settings'],
  ],
  shared: [
    ['notifications', 'Notifications', 'Cross-role activity inbox', 'list'],
    ['settings-home', 'Settings home', 'Role-aware preference overview', 'settings'],
    ['account', 'Account', 'Email, password, and account actions', 'settings'],
    ['profile-settings', 'Profile settings', 'Personal details and avatar', 'settings'],
    ['notification-settings', 'Notification settings', 'Domain and channel preferences', 'settings'],
    ['privacy-settings', 'Privacy settings', 'Visibility and safety controls', 'settings'],
    ['pending-approval', 'Pending approval', 'Review status and guidance', 'success'],
    ['not-found', 'Not found', 'Recovery from an invalid destination', 'success'],
  ],
};

export const getPrototypeScreen = (experience, id) =>
  (PROTOTYPE_CATALOG[experience] || []).find(([screenId]) => screenId === id);

// Live parity uses the production routes themselves. Dynamic detail screens
// intentionally open their owning list page so a real record can be selected;
// this avoids inventing IDs or displaying fake production data.
const PROTOTYPE_ROUTES = {
  public: {
    landing: '/', about: '/about', donations: '/donations', store: '/store',
    product: '/store', cart: '/store/cart', orders: '/store/orders',
    'order-confirmation': '/store/orders', login: '/login', register: '/register',
    'forgot-password': '/forgot-password', 'reset-password': '/forgot-password',
    'verify-email': '/verify-email', faq: '/faq', terms: '/terms', privacy: '/privacy',
    conduct: '/code-of-conduct',
  },
  eaglet: {
    home: '/eaglet/dashboard', onboarding: '/onboarding', profile: '/mentee-profile',
    nest: '/eaglet/nest', 'nest-community': '/eaglet/nest',
    'mentor-profile': '/eaglet/nest', 'join-nest': '/eaglet/nest',
    requests: '/eaglet/my-requests', learn: '/eaglet/assignments',
    'assignment-detail': '/eaglet/assignments', 'content-viewer': '/eaglet/assignments',
    quiz: '/eaglet/assignments', leaderboard: '/eaglet/leaderboard', badges: '/eaglet/badges',
    'mentor-application': '/eaglet/mentor-application', messages: '/eaglet/messages',
    resources: '/eaglet/resources', settings: '/settings',
  },
  eagle: {
    home: '/eagle/dashboard', profile: '/mentor-profile', nest: '/eagle/nests',
    'nest-community': '/eagle/nests', grading: '/eagle/grading', requests: '/eagle/nests',
    program: '/eagle/nests', enrollments: '/eagle/nests', learn: '/eagle/content',
    'content-upload': '/eagle/content/upload', 'content-viewer': '/eagle/content',
    leaderboard: '/eagle/leaderboard', eaglets: '/eagle/eaglets', messages: '/eagle/messages',
    resources: '/eagle/resources', settings: '/settings',
  },
  admin: {
    home: '/admin/dashboard', kyc: '/admin/kyc', 'kyc-detail': '/admin/kyc',
    users: '/admin/users', team: '/admin/team', 'role-requests': '/admin/team/requests',
    'mentor-applications': '/admin/mentor-applications', nests: '/admin/nests',
    'nest-detail': '/admin/nests', messages: '/admin/messages', learn: '/admin/content',
    'content-upload': '/admin/content/upload', store: '/admin/store',
    orders: '/admin/store/orders', donations: '/admin/donations',
    points: '/settings/admin/points', settings: '/settings/admin/platform',
  },
  shared: {
    notifications: '/notifications', 'settings-home': '/settings', account: '/settings/account',
    'profile-settings': '/settings/profile', 'notification-settings': '/settings/notifications',
    'privacy-settings': '/settings/privacy', 'pending-approval': '/pending-approval',
    'not-found': '/this-page-does-not-exist',
  },
};

export const getPrototypeRoute = (experience, id) =>
  PROTOTYPE_ROUTES[experience]?.[id] || '/';
